spring:
  datasource:
    #h2 setting
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:homework29
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

#logging.level:
#  org.hibernate.SQL: debug

server:
  port: 8081